{
 "title": "Logging Dashboard via Loki",
 "description": "Logging Dashboard via Loki using cluster, job, and pod labels",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Total Count of logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=\"$cluster\", job=\"vault_audit\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({cluster=\"$cluster\", job=\"vault_audit\", pod=~\"$pod\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{cluster=\"$cluster\", job=\"vault_audit\", pod=~\"$pod\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  }
 ]
}