loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    # HIGH VOLUME SETTINGS FOR VAULT AUDIT LOGS
    ingestion_rate_mb: 50           # Increase from 4MB to 50MB per second
    ingestion_burst_size_mb: 100    # Allow 100MB bursts
    per_stream_rate_limit: 20MB     # Increase from 3MB to 20MB per stream
    per_stream_rate_limit_burst: 40MB # Allow 40MB stream bursts
    max_line_size: 2MB              # Support large Vault audit log entries
    max_entries_limit_per_query: 50000  # Handle large query results
    max_query_parallelism: 256      # Better query performance
    split_queries_by_interval: 30m  # Optimize large queries
  ruler:
    enable_api: true

# Storage configuration
minio:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi  # Increase storage for high volume
    storageClass: hostpath

deploymentMode: SimpleScalable

# MICROSERVICE COMPONENTS with minimal resource allocation for Docker Desktop
write:
  replicas: 2
  resources:
    requests:
      cpu: 300m         # Reduced from 1000m
      memory: 512Mi     # Reduced from 2Gi

read:
  replicas: 2
  resources:
    requests:
      cpu: 300m         # Reduced from 500m
      memory: 512Mi     # Reduced from 1Gi

backend:
  replicas: 1
  resources:
    requests:
      cpu: 500m         # Reduced from 2000m
      memory: 1Gi       # Reduced from 4Gi

gateway:
  replicas: 1
  resources:
    requests:
      cpu: 200m         # Reduced from 500m
      memory: 256Mi     # Reduced from 1Gi

# DOCKER DESKTOP OPTIMIZED - Minimal memory allocation
chunksCache:
  enabled: true
  replicas: 1
  allocatedMemory: 256   # 256MB - aggressive reduction
  resources:
    requests:
      cpu: 200m           # Reduced CPU too
      memory: 512Mi       # Much smaller memory request

resultsCache:
  enabled: true
  replicas: 1
  allocatedMemory: 128   # 128MB - very small
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

indexCache:
  enabled: true
  replicas: 1
  allocatedMemory: 64    # 64MB - minimal
  resources:
    requests:
      cpu: 200m
      memory: 128Mi

service:
  type: LoadBalancer
  port: 3100