# Source: grafana/templates/loki.yaml 

service:
  type: LoadBalancer
  port: 3100

image:
    repository: grafana/loki
    tag: 2.9.3
    pullPolicy: IfNotPresent
    
loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: 2022-06-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 500m
    memory: 512Mi